config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root to: "journal_entries#index"
  devise_for :users
  resources :journal_entries  
  resource :two_factor_authentication, only: [:show, :create], controller: 'two_factor_authentication'
   #root "pages#about" # <-- Change this line

  get "about", to: "pages#about"
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  # Add this line
  belongs_to :user

  # Optional: Add validations for title and content
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  encrypts :content
end

app/controllers/journal_entries_controller.rb
# app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :authenticate_user!
  
  # GET /journal_entries or /journal_entries.json
  def index
    @journal_entries = policy_scope(JournalEntry)
  end

  # GET /journal_entries/1 or /journal_entries/1.json
  def show
    @journal_entry = JournalEntry.find(params[:id])
    authorize @journal_entry
  end

  # GET /journal_entries/new
  def new
    @journal_entry = current_user.journal_entries.build
  end

  # GET /journal_entries/1/edit
  def edit
    @journal_entry = JournalEntry.find(params[:id])
    authorize @journal_entry
  end

  # POST /journal_entries or /journal_entries.json
  def create
    @journal_entry = current_user.journal_entries.build(journal_entry_params)
    
    if @journal_entry.save
      redirect_to journal_entry_url(@journal_entry), notice: "Journal entry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /journal_entries/1 or /journal_entries/1.json
  def update
    @journal_entry = JournalEntry.find(params[:id])
    authorize @journal_entry
    
    if @journal_entry.update(journal_entry_params)
      redirect_to journal_entry_url(@journal_entry), notice: "Journal entry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /journal_entries/1 or /journal_entries/1.json
  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    authorize @journal_entry
    
    @journal_entry.destroy!
    redirect_to journal_entries_url, notice: "Journal entry was successfully destroyed."
  end

  private

    def journal_entry_params
      params.require(:journal_entry).permit(:title, :content)
    end
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/journal_entries/_form.html.erb
<%# app/views/journal_entries/_form.html.erb %>
<%= form_with(model: journal_entry) do |form| %>
  <% if journal_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
        <% journal_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/journal_entries/edit.html.erb
<%# app/views/journal_entries/edit.html.erb %>
<h1>Editing journal entry</h1>

<%= render "form", journal_entry: @journal_entry %>

<br>

<div>
  <%= link_to "Show this journal entry", @journal_entry %> |
  <%= link_to "Back to journal entries", journal_entries_path %>
</div>

app/views/journal_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journal Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td><%= journal_entry.title %></td>
        <td><%= journal_entry.body %></td>
        <td><%= link_to 'Show', journal_entry %></td>
        <td><%= link_to 'Edit', edit_journal_entry_path(journal_entry) %></td>
        <td><%= link_to 'Destroy', journal_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal Entry', new_journal_entry_path %>

app/views/journal_entries/new.html.erb
<%# app/views/journal_entries/new.html.erb %>
<h1>New journal entry</h1>

<%= render "form", journal_entry: @journal_entry %>

<br>

<div>
  <%= link_to "Back to journal entries", journal_entries_path %>
</div>

app/views/journal_entries/show.html.erb
<%# app/views/journal_entries/show.html.erb %>
<p id="notice"><%= notice %></p>

<h1><%= @journal_entry.title %></h1>

<p>
  <%= @journal_entry.body %>
</p>

<div>
  <%= simple_format(@journal_entry.content) %>
</div>

<div>
  <%= link_to "Edit this journal entry", edit_journal_entry_path(@journal_entry) %> |
  <%= button_to "Delete this journal entry", @journal_entry, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

<div>
  <%= link_to "Back to journal entries", journal_entries_path %>
</div>